version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ades/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ades/data/mariadb'

networks:
  inception:
    driver: bridge


